import React from 'react';
import type { ResearchReport } from '../services/api';
import { useWatchlist } from '../hooks/useWatchlist';

const _DISCLAIMER =
  "⚠️ This report is generated by an AI system for informational purposes only. It does not constitute financial advice, investment recommendation, or a solicitation to buy or sell any security. Past performance is not indicative of future results. Always consult a qualified financial advisor before making investment decisions.";

interface ReportViewProps {
  report: ResearchReport;
  onBack?: () => void;
}

export const ReportView: React.FC<ReportViewProps> = ({ report, onBack }) => {
  const { ticker, exchange, generated_at, financials, news, synthesis, processing_time_seconds } = report;
  const { addTicker, removeTicker, isWatched, updateVerdict } = useWatchlist();
  const watched = isWatched(ticker);

  const handleWatchToggle = () => {
    if (watched) {
      removeTicker(ticker);
    } else {
      addTicker(ticker, {
        lastVerdict: synthesis?.verdict,
        companyName: financials?.company_name,
      });
    }
    // Keep lastVerdict in sync when watching an already-analysed report
    if (!watched && synthesis?.verdict) {
      updateVerdict(ticker, synthesis.verdict, financials?.company_name);
    }
  };

  const handleExportPdf = () => {
    window.print();
  };

  // Format Helper for large currencies
  const formatCurrency = (val: number | null, data_source: string) => {
    if (val === null || val === undefined) return 'N/A';
    const isLkr = data_source === 'cse_csv';
    const prefix = isLkr ? 'Rs. ' : '$';
    if (val >= 1_000_000_000_000) {
      return `${prefix}${(val / 1_000_000_000_000).toFixed(2)}T`;
    }
    if (val >= 1_000_000_000) {
      return `${prefix}${(val / 1_000_000_000).toFixed(2)}B`;
    }
    if (val >= 1_000_000) {
      return `${prefix}${(val / 1_000_000).toFixed(1)}M`;
    }
    return `${prefix}${val.toLocaleString()}`;
  };

  // Format Helper for PE
  const formatPE = (pe: number | null) => {
    if (pe === null || pe === undefined) return 'N/A';
    return pe.toFixed(2);
  };

  // Helper for Percentage
  const formatPercent = (pct: number | null) => {
    if (pct === null || pct === undefined) return 'N/A';
    return `${pct.toFixed(2)}%`;
  };

  // Verdict Colors mapping
  const verdictColors = {
    BUY: {
      bg: 'bg-emerald-500/10 border-emerald-500/30 text-emerald-400',
      fill: 'fill-emerald-400',
      badge: 'bg-emerald-500/20 text-emerald-300',
      text: 'text-emerald-400',
      gradient: 'from-emerald-600/20 to-teal-600/20 border-emerald-500/30 shadow-emerald-500/5',
      glow: 'shadow-emerald-500/10',
    },
    HOLD: {
      bg: 'bg-amber-500/10 border-amber-500/30 text-amber-400',
      fill: 'fill-amber-400',
      badge: 'bg-amber-500/20 text-amber-300',
      text: 'text-amber-400',
      gradient: 'from-amber-600/20 to-orange-600/20 border-amber-500/30 shadow-amber-500/5',
      glow: 'shadow-amber-500/10',
    },
    SELL: {
      bg: 'bg-rose-500/10 border-rose-500/30 text-rose-400',
      fill: 'fill-rose-400',
      badge: 'bg-rose-500/20 text-rose-300',
      text: 'text-rose-400',
      gradient: 'from-rose-600/20 to-red-600/20 border-rose-500/30 shadow-rose-500/5',
      glow: 'shadow-rose-500/10',
    },
  };

  const vCol = synthesis ? verdictColors[synthesis.verdict] : verdictColors.HOLD;

  // Sentiment Color mapping
  const sentimentBadges = {
    Positive: 'bg-emerald-500/15 text-emerald-400 border border-emerald-500/20',
    Neutral: 'bg-slate-500/15 text-slate-300 border border-slate-500/20',
    Negative: 'bg-rose-500/15 text-rose-400 border border-rose-500/20',
  };

  return (
    <div className="w-full max-w-5xl mx-auto p-4 md:p-8 space-y-8 animate-fade-in">
      {/* Back button, action buttons, and Metadata Header */}
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
        <div className="flex items-center gap-2 no-print">
          {onBack && (
            <button
              onClick={onBack}
              className="flex items-center gap-2 px-4 py-2 rounded-xl text-sm font-medium text-slate-400 bg-[rgba(255,255,255,0.03)] border border-[rgba(255,255,255,0.06)] hover:bg-[rgba(255,255,255,0.07)] hover:text-slate-200 transition-all cursor-pointer"
            >
              ← Back to Search
            </button>
          )}
          {/* Watch / Unwatch toggle */}
          <button
            onClick={handleWatchToggle}
            title={watched ? 'Remove from Watchlist' : 'Add to Watchlist'}
            className={`flex items-center gap-1.5 px-4 py-2 rounded-xl text-sm font-semibold border transition-all cursor-pointer ${
              watched
                ? 'bg-amber-500/20 border-amber-500/40 text-amber-300 hover:bg-amber-500/30'
                : 'bg-[rgba(255,255,255,0.03)] border-[rgba(255,255,255,0.06)] text-slate-400 hover:bg-amber-500/10 hover:text-amber-400 hover:border-amber-500/25'
            }`}
          >
            {watched ? '★ Watching' : '⭐ Watch'}
          </button>
          {/* Export PDF */}
          <button
            onClick={handleExportPdf}
            title="Export report as PDF"
            className="flex items-center gap-1.5 px-4 py-2 rounded-xl text-sm font-semibold text-slate-400 bg-[rgba(255,255,255,0.03)] border border-[rgba(255,255,255,0.06)] hover:bg-indigo-500/10 hover:text-indigo-400 hover:border-indigo-500/25 transition-all cursor-pointer"
          >
            🖨️ Export PDF
          </button>
        </div>
        <div className="text-right md:text-right w-full md:w-auto">
          <p className="text-xs text-slate-500">
            Generated at: <span className="text-slate-400">{new Date(generated_at).toLocaleString()}</span>
          </p>
          {processing_time_seconds && (
            <p className="text-xs text-slate-500">
              Pipeline Duration: <span className="text-indigo-400 font-semibold">{processing_time_seconds}s</span>
            </p>
          )}
        </div>
      </div>

      {/* Title Card */}
      <div className="bg-[rgba(26,26,46,0.5)] border border-[rgba(255,255,255,0.08)] rounded-3xl p-6 md:p-8 relative overflow-hidden flex flex-col md:flex-row justify-between items-start md:items-center gap-6 shadow-xl">
        <div className="absolute top-0 right-0 w-64 h-64 bg-indigo-500/5 rounded-full blur-3xl -z-10"></div>
        <div className="space-y-2">
          <div className="flex items-center gap-3">
            <span className="text-3xl font-black tracking-tight text-white">{ticker}</span>
            <span className="px-3 py-1 rounded-full text-xs font-semibold bg-indigo-500/10 text-indigo-300 border border-indigo-500/20">
              {exchange}
            </span>
          </div>
          <h2 className="text-xl font-bold text-slate-300">
            {financials?.company_name || ticker}
          </h2>
          <div className="flex items-center gap-2">
            <span className="text-xs text-slate-500">Data Source:</span>
            <span className="text-xs font-medium text-slate-400 uppercase">
              {financials?.data_source === 'cse_csv' ? 'Colombo SE CSV Fallback' : 'yfinance API (Real-Time)'}
            </span>
          </div>
        </div>

        {/* Live Price display if available */}
        {financials?.current_price && (
          <div className="text-right space-y-1">
            <p className="text-xs text-slate-500 uppercase tracking-widest font-semibold">Current Price</p>
            <p className="text-3xl font-extrabold text-white">
              {financials.data_source === 'cse_csv' ? 'Rs. ' : '$'}
              {financials.current_price.toLocaleString()}
            </p>
          </div>
        )}
      </div>

      {/* Main Grid Layout */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
        
        {/* RECOMMENDATION CARD (BUY/HOLD/SELL) */}
        <div className={`md:col-span-3 bg-gradient-to-br ${vCol.gradient} border rounded-3xl p-6 md:p-8 shadow-2xl relative`}>
          <div className="flex flex-col md:flex-row items-start md:items-center justify-between gap-6">
            <div className="space-y-4">
              <span className="text-xs font-bold uppercase tracking-wider text-slate-400">Research Recommendation</span>
              <div className="flex items-center gap-4">
                <span className={`text-5xl font-black ${vCol.text} tracking-tighter`}>
                  {synthesis?.verdict || 'HOLD'}
                </span>
                <span className={`px-4 py-1.5 rounded-full text-xs font-bold ${vCol.badge}`}>
                  Confidence: {synthesis?.confidence || 'Medium'}
                </span>
              </div>
              <p className="text-slate-200 text-base leading-relaxed md:max-w-3xl">
                {synthesis?.reasoning || 'No analysis reasoning generated.'}
              </p>
            </div>

            {/* Custom SVG confidence dial */}
            <div className="hidden md:block flex-shrink-0">
              <svg className="w-24 h-24" viewBox="0 0 100 100">
                <circle cx="50" cy="50" r="40" stroke="rgba(255,255,255,0.05)" strokeWidth="8" fill="none" />
                <circle
                  cx="50"
                  cy="50"
                  r="40"
                  className={vCol.text}
                  stroke="currentColor"
                  strokeWidth="8"
                  fill="none"
                  strokeDasharray="251.2"
                  strokeDashoffset={
                    synthesis?.confidence === 'High'
                      ? '50'
                      : synthesis?.confidence === 'Medium-High'
                      ? '100'
                      : synthesis?.confidence === 'Medium'
                      ? '150'
                      : '200'
                  }
                  strokeLinecap="round"
                  transform="rotate(-90 50 50)"
                />
                <text x="50" y="55" textAnchor="middle" className="fill-white font-bold text-xs">
                  {synthesis?.confidence}
                </text>
              </svg>
            </div>
          </div>
        </div>

        {/* FINANCIAL FUNDAMENTALS CARD */}
        <div className="md:col-span-2 bg-[rgba(26,26,46,0.4)] border border-[rgba(255,255,255,0.06)] rounded-3xl p-6 md:p-8 space-y-6 shadow-lg">
          <h3 className="text-lg font-bold text-white border-b border-white/5 pb-3">
            📊 Fundamentals & Valuation
          </h3>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-x-8 gap-y-4">
            
            {/* Market Cap */}
            <div className="flex justify-between items-center py-2 border-b border-white/5">
              <span className="text-sm text-slate-400">Market Cap</span>
              <span className="text-sm font-semibold text-slate-100">
                {formatCurrency(financials?.market_cap || null, financials?.data_source || 'yfinance')}
              </span>
            </div>

            {/* PE Ratio */}
            <div className="flex justify-between items-center py-2 border-b border-white/5">
              <span className="text-sm text-slate-400">P/E Ratio</span>
              <span className="text-sm font-semibold text-slate-100">
                {formatPE(financials?.pe_ratio || null)}
              </span>
            </div>

            {/* EPS */}
            <div className="flex justify-between items-center py-2 border-b border-white/5">
              <span className="text-sm text-slate-400">EPS (TTM)</span>
              <span className="text-sm font-semibold text-slate-100">
                {financials?.eps !== null && financials?.eps !== undefined ? financials.eps.toFixed(2) : 'N/A'}
              </span>
            </div>

            {/* Total Revenue */}
            <div className="flex justify-between items-center py-2 border-b border-white/5">
              <span className="text-sm text-slate-400">Revenue (TTM)</span>
              <span className="text-sm font-semibold text-slate-100">
                {formatCurrency(financials?.revenue || null, financials?.data_source || 'yfinance')}
              </span>
            </div>

            {/* Debt to Equity */}
            <div className="flex justify-between items-center py-2 border-b border-white/5">
              <span className="text-sm text-slate-400">Debt/Equity</span>
              <span className="text-sm font-semibold text-slate-100">
                {financials?.debt_to_equity !== null && financials?.debt_to_equity !== undefined
                  ? financials.debt_to_equity.toFixed(2)
                  : 'N/A'}
              </span>
            </div>

            {/* Dividend Yield */}
            <div className="flex justify-between items-center py-2 border-b border-white/5">
              <span className="text-sm text-slate-400">Dividend Yield</span>
              <span className="text-sm font-semibold text-slate-100">
                {formatPercent(financials?.dividend_yield || null)}
              </span>
            </div>
          </div>

          {/* 52-Week Range Custom Slider */}
          {financials?.fifty_two_week_low && financials?.fifty_two_week_high && financials?.current_price && (
            <div className="space-y-2 pt-2">
              <div className="flex justify-between text-xs text-slate-400">
                <span>52W Low: {financials.fifty_two_week_low}</span>
                <span>52W High: {financials.fifty_two_week_high}</span>
              </div>
              <div className="relative h-2 bg-slate-800 rounded-full overflow-hidden">
                <div
                  className="absolute top-0 bottom-0 bg-indigo-500 rounded-full"
                  style={{
                    left: '0%',
                    width: `${
                      ((financials.current_price - financials.fifty_two_week_low) /
                        (financials.fifty_two_week_high - financials.fifty_two_week_low)) *
                      100
                    }%`,
                  }}
                ></div>
              </div>
              <p className="text-center text-xs text-indigo-400 font-medium">
                Current: {financials.current_price}
              </p>
            </div>
          )}

          {/* Valuation Commentary */}
          {financials?.valuation_commentary && (
            <div className="mt-4 p-4 rounded-xl bg-white/5 border border-white/5">
              <p className="text-xs font-bold text-indigo-400 uppercase tracking-widest mb-1">
                Valuation Commentary
              </p>
              <p className="text-sm text-slate-300 leading-relaxed">
                {financials.valuation_commentary}
              </p>
            </div>
          )}
        </div>

        {/* NEWS & SENTIMENT CARD */}
        <div className="bg-[rgba(26,26,46,0.4)] border border-[rgba(255,255,255,0.06)] rounded-3xl p-6 md:p-8 space-y-6 shadow-lg flex flex-col justify-between">
          <div className="space-y-6">
            <h3 className="text-lg font-bold text-white border-b border-white/5 pb-3">
              📰 Recent News & Sentiment
            </h3>

            {/* News Articles List */}
            <div className="space-y-4 max-h-[350px] overflow-y-auto pr-2">
              {news?.headlines && news.headlines.length > 0 ? (
                news.headlines.map((item, idx) => (
                  <div key={idx} className="space-y-1.5 p-3 rounded-xl hover:bg-white/5 transition-all">
                    <div className="flex justify-between items-center">
                      <span className="text-[10px] text-slate-500 font-bold uppercase">{item.source}</span>
                      <span className={`px-2 py-0.5 rounded text-[9px] font-bold ${sentimentBadges[item.sentiment]}`}>
                        {item.sentiment}
                      </span>
                    </div>
                    <a
                      href={item.url}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="block text-sm text-slate-200 hover:text-indigo-400 font-medium line-clamp-2 transition-all"
                    >
                      {item.title}
                    </a>
                  </div>
                ))
              ) : (
                <p className="text-sm text-slate-500 italic text-center py-4">No recent news headlines available.</p>
              )}
            </div>
          </div>

          {/* Aggregated Sentiment Indicator */}
          {news?.overall_sentiment && (
            <div className="pt-4 border-t border-white/5 flex items-center justify-between">
              <span className="text-sm font-semibold text-slate-400">Overall Sentiment</span>
              <span className={`px-3 py-1 rounded-full text-xs font-bold ${sentimentBadges[news.overall_sentiment]}`}>
                {news.overall_sentiment}
              </span>
            </div>
          )}
        </div>

        {/* RISK FACTORS & SPECIFIC RISK DETAILS */}
        <div className="md:col-span-2 bg-[rgba(26,26,46,0.4)] border border-[rgba(255,255,255,0.06)] rounded-3xl p-6 md:p-8 space-y-6 shadow-lg">
          <h3 className="text-lg font-bold text-white border-b border-white/5 pb-3">
            ⚠️ Risk Factors & Threats
          </h3>
          <div className="space-y-4">
            {synthesis?.risks && synthesis.risks.length > 0 ? (
              synthesis.risks.map((risk, idx) => (
                <div key={idx} className="flex gap-4 p-4 rounded-xl bg-rose-500/5 border border-rose-500/10">
                  <span className="text-lg text-rose-400">☠️</span>
                  <p className="text-sm text-slate-300 leading-relaxed">{risk}</p>
                </div>
              ))
            ) : (
              <p className="text-sm text-slate-500 italic">No specific risk factors generated by analyst agents.</p>
            )}
          </div>
        </div>

        {/* KEY EVENTS EXTRACTION CARD */}
        <div className="bg-[rgba(26,26,46,0.4)] border border-[rgba(255,255,255,0.06)] rounded-3xl p-6 md:p-8 space-y-6 shadow-lg">
          <h3 className="text-lg font-bold text-white border-b border-white/5 pb-3">
            ⚡ Extracted Key Events
          </h3>
          <div className="space-y-4">
            {news?.key_events && news.key_events.length > 0 ? (
              news.key_events.map((event, idx) => (
                <div key={idx} className="flex gap-3 items-start">
                  <span className="text-indigo-400 mt-1">✦</span>
                  <p className="text-sm text-slate-300 leading-relaxed">{event}</p>
                </div>
              ))
            ) : (
              <p className="text-sm text-slate-500 italic">No major catalyst events identified in current cycle.</p>
            )}
          </div>
        </div>

        {/* Legal Disclaimer block */}
        <div className="md:col-span-3 p-6 rounded-2xl bg-[rgba(239,68,68,0.03)] border border-rose-500/10">
          <p className="text-[11px] text-slate-500 text-center leading-relaxed">
            {synthesis?.disclaimer || _DISCLAIMER}
          </p>
        </div>
      </div>
    </div>
  );
};
export default ReportView;
