"""
agents/synthesis_agent.py
Phase 4: Synthesis Agent

Combines the outputs of the News Agent and Financials Agent to produce
a structured research verdict:
  - Verdict: BUY | HOLD | SELL
  - Confidence: Low | Medium | Medium-High | High
  - Reasoning: 2-3 sentence explanation
  - Risks: list of 3 concrete risk factors
  - Disclaimer: auto-injected legal disclaimer

The agent calls Groq in JSON mode. If the response is malformed it retries
up to 3 times with progressively more explicit prompts. On total failure it
returns a safe HOLD verdict with an error note.

Public API:
    run_synthesis_agent(news, financials) -> SynthesisAgentOutput
"""

import json
import logging
from typing import Optional

from core.config import get_settings
from core.llm_client import chat_completion
from core.models import (
    FinancialsAgentOutput,
    NewsAgentOutput,
    Confidence,
    SynthesisAgentOutput,
    Verdict,
)

logger = logging.getLogger(__name__)
settings = get_settings()

# ─── Disclaimer (auto-injected on every report) ───────────────────────────────
_DISCLAIMER = (
    "⚠️ This report is generated by an AI system for informational purposes only. "
    "It does not constitute financial advice, investment recommendation, or a solicitation "
    "to buy or sell any security. Past performance is not indicative of future results. "
    "Always consult a qualified financial advisor before making investment decisions."
)

# ─── System prompt ────────────────────────────────────────────────────────────
_SYNTHESIS_SYSTEM = """
You are a senior equity research analyst at a top-tier investment bank.
You will receive:
  1. Recent news headlines and their sentiment analysis for a stock
  2. Key financial metrics for that stock

Your task is to synthesise this information and produce a research verdict.

IMPORTANT RULES:
- Output ONLY a valid JSON object — no markdown, no explanation, no preamble.
- The JSON must contain exactly these four keys: verdict, confidence, reasoning, risks
- verdict must be exactly one of: "BUY", "HOLD", or "SELL"
- confidence must be exactly one of: "Low", "Medium", "Medium-High", "High"
- reasoning must be a string of 2-3 sentences explaining your verdict
- risks must be a JSON array of exactly 3 strings, each describing a specific risk
- Do NOT include any financial advice disclaimer in your output
- If data is limited (many N/A fields), still provide your best assessment
  and reflect the uncertainty in the confidence level (use Low or Medium)

Example output format (replace values with your analysis):
{
  "verdict": "HOLD",
  "confidence": "Medium",
  "reasoning": "The company shows stable earnings growth but faces headwinds from regulatory scrutiny. Current valuation appears fair relative to peers. The mixed news sentiment suggests near-term uncertainty.",
  "risks": [
    "Regulatory pressure could increase compliance costs significantly",
    "Slowing revenue growth may compress margins over the next 2 quarters",
    "High debt-to-equity ratio limits financial flexibility in a rising rate environment"
  ]
}
"""


# ─── Input formatter ──────────────────────────────────────────────────────────

def _format_news_section(news: Optional[NewsAgentOutput]) -> str:
    """Convert NewsAgentOutput into a readable string for the LLM."""
    if news is None:
        return "NEWS DATA: Not available\n"

    lines = [
        f"NEWS ANALYSIS FOR {news.ticker}:",
        f"  Overall Sentiment: {news.overall_sentiment.value}",
        f"  Headlines analysed: {len(news.headlines)}",
    ]

    if news.headlines:
        lines.append("  Recent headlines:")
        for i, h in enumerate(news.headlines[:5], 1):
            lines.append(f"    {i}. [{h.sentiment.value}] {h.title} (Source: {h.source})")

    if news.key_events:
        lines.append("  Key events identified:")
        for e in news.key_events:
            lines.append(f"    • {e}")

    return "\n".join(lines)


def _format_financials_section(fin: Optional[FinancialsAgentOutput]) -> str:
    """Convert FinancialsAgentOutput into a readable string for the LLM."""
    if fin is None:
        return "FINANCIAL DATA: Not available\n"

    def fmt(val, suffix=""):
        if val is None:
            return "N/A"
        if suffix == "B" and val >= 1_000_000_000:
            return f"${val / 1_000_000_000:.2f}B"
        if suffix == "M" and val >= 1_000_000:
            return f"${val / 1_000_000:.1f}M"
        if suffix == "%":
            return f"{val:.2f}%"
        return f"{val:.2f}"

    lines = [
        f"FINANCIAL DATA FOR {fin.ticker} ({fin.exchange}):",
        f"  Company: {fin.company_name}",
        f"  Data source: {fin.data_source}",
        f"  Current Price: {fmt(fin.current_price)}",
        f"  Market Cap: {fmt(fin.market_cap, 'B')}",
        f"  P/E Ratio: {fmt(fin.pe_ratio)}",
        f"  EPS: {fmt(fin.eps)}",
        f"  Revenue (TTM): {fmt(fin.revenue, 'B')}",
        f"  Debt/Equity: {fmt(fin.debt_to_equity)}",
        f"  Dividend Yield: {fmt(fin.dividend_yield, '%')}",
        f"  52-Week High: {fmt(fin.fifty_two_week_high)}",
        f"  52-Week Low: {fmt(fin.fifty_two_week_low)}",
    ]

    if fin.valuation_commentary:
        lines.append(f"\n  Analyst note: {fin.valuation_commentary}")

    return "\n".join(lines)


# ─── JSON parser with strict validation ───────────────────────────────────────

def _parse_verdict_json(raw: str) -> Optional[dict]:
    """
    Parse and validate the raw LLM string as a synthesis verdict JSON.
    Returns the dict if valid, or None if malformed.
    """
    try:
        # Strip any accidental markdown fences
        clean = raw.strip()
        if clean.startswith("```"):
            clean = clean.split("```")[1]
            if clean.startswith("json"):
                clean = clean[4:]
        clean = clean.strip()

        data = json.loads(clean)

        # Validate required keys
        required = {"verdict", "confidence", "reasoning", "risks"}
        if not required.issubset(data.keys()):
            logger.warning("Synthesis JSON missing keys: %s", required - data.keys())
            return None

        # Validate enum values
        if data["verdict"] not in ("BUY", "HOLD", "SELL"):
            logger.warning("Invalid verdict: %s", data["verdict"])
            return None

        if data["confidence"] not in ("Low", "Medium", "Medium-High", "High"):
            logger.warning("Invalid confidence: %s", data["confidence"])
            return None

        if not isinstance(data["risks"], list) or len(data["risks"]) == 0:
            logger.warning("Risks must be a non-empty list")
            return None

        return data

    except (json.JSONDecodeError, KeyError, TypeError) as exc:
        logger.warning("Synthesis JSON parse error: %s | raw: %s", exc, raw[:200])
        return None


# ─── Fallback verdict ─────────────────────────────────────────────────────────

def _fallback_output(ticker: str, reason: str) -> SynthesisAgentOutput:
    """Return a safe HOLD verdict when the LLM completely fails."""
    return SynthesisAgentOutput(
        verdict=Verdict.HOLD,
        confidence=Confidence.LOW,
        reasoning=(
            f"Unable to generate a full analysis for {ticker} at this time. "
            f"Reason: {reason}. "
            "A HOLD verdict is returned as a safe default — please retry or "
            "consult a financial advisor."
        ),
        risks=[
            "AI analysis unavailable — treat this report with caution",
            "Verify all data independently before making any decisions",
            "Market conditions may have changed since data was fetched",
        ],
        disclaimer=_DISCLAIMER,
    )


# ─── Public entry point ───────────────────────────────────────────────────────

async def run_synthesis_agent(
    news: Optional[NewsAgentOutput],
    financials: Optional[FinancialsAgentOutput],
) -> SynthesisAgentOutput:
    """
    Synthesise news and financial data into a BUY/HOLD/SELL research verdict.

    Args:
        news:       Output from the News Agent (may be None on agent failure)
        financials: Output from the Financials Agent (may be None on agent failure)

    Returns:
        SynthesisAgentOutput with verdict, confidence, reasoning, risks,
        and auto-injected disclaimer.
    """
    ticker = (financials and financials.ticker) or (news and news.ticker) or "UNKNOWN"

    if not settings.groq_api_key:
        logger.error("GROQ_API_KEY not set — cannot run Synthesis Agent")
        return _fallback_output(ticker, "Groq API key not configured")

    # ── Build user message ────────────────────────────────────────────────────
    news_section = _format_news_section(news)
    fin_section = _format_financials_section(financials)

    user_message = (
        f"{news_section}\n\n"
        f"{fin_section}\n\n"
        "Based on the above data, produce your research verdict as a JSON object."
    )

    # ── Attempt with up to 3 retries ─────────────────────────────────────────
    current_prompt = user_message
    for attempt in range(1, 4):
        logger.info("Synthesis Agent attempt %d/3 for %s", attempt, ticker)
        try:
            raw = await chat_completion(
                _SYNTHESIS_SYSTEM,
                current_prompt,
                json_mode=True,
                temperature=0.15,
                max_tokens=512,
                max_retries=2,
            )
            parsed = _parse_verdict_json(raw)

            if parsed:
                return SynthesisAgentOutput(
                    verdict=Verdict(parsed["verdict"]),
                    confidence=Confidence(parsed["confidence"]),
                    reasoning=parsed["reasoning"].strip(),
                    risks=[r.strip() for r in parsed["risks"][:3]],
                    disclaimer=_DISCLAIMER,
                )

            # Validation failed — retry with stricter instruction
            logger.warning("Synthesis attempt %d returned invalid JSON — retrying", attempt)
            current_prompt = (
                user_message
                + f"\n\nIMPORTANT: Your previous response was invalid. "
                  f"Return ONLY a valid JSON object with keys: "
                  f"verdict (BUY/HOLD/SELL), confidence (Low/Medium/Medium-High/High), "
                  f"reasoning (string), risks (array of 3 strings). "
                  f"No other text whatsoever."
            )

        except Exception as exc:
            logger.error("Synthesis Agent error on attempt %d: %s", attempt, exc)
            if attempt == 3:
                return _fallback_output(ticker, str(exc))

    return _fallback_output(ticker, "All 3 synthesis attempts returned invalid JSON")
